### ISSUE TITLE
allow editing (and other todo)

### ISSUE THREAD

**Issue by ohnx** [ohnx/easyblog#1]
- [ ] create responsive admin page
 - [ ] list posts on admin page
 - [ ] add modes for editing and deletion on admin page
 - [ ] add bar underneath post title allowing hiding the post, editing the post, and printing the post?

**Comment by ohnx** [comment]
admin page:
settings exists? load it.
no exist? prompt

**Comment by ohnx** [comment]
yay sleep
